### ISSUE TITLE
Purchase Order

### ISSUE THREAD

**Issue by EpicPantalones** [EpicPantalones/AutoFrog#3]
Purchasing info for the approved items. 15 items comes out to $206.37. Will wait for confirmation before purchase. Do not close this issue.

**Comment by sirgunthercakes** [comment]
approve

**Comment by EpicPantalones** [comment]
Order# 113-9573016-7701869 placed. Items arriving July 3 and July 6. Will post updates

**Comment by EpicPantalones** [comment]
The following arrived today (now 4/13):
2 pin BTF-Lightning connectors
12v Power Supply
AZDelivery Humidity sensor
Suction cups

**Comment by sirgunthercakes** [comment]
arrived 7/5
3 pin BTF lightning connectors
16 ga cable
20 ga cable
3 pin insulated cable
power rocker ac input
ac output plugs
5 volt converter
standoffs
8 channel relay
rpi zero-w
